file(READ "${SOURCE_DIR}/src/AndroidGribSettings.cpp" settings)
file(READ "${SOURCE_DIR}/src/AndroidGribGenerator.cpp" generator)
file(READ "${SOURCE_DIR}/src/GribUIDialog.cpp" panel)
foreach(text "Save and close" "Cancel" "bool accepted = false" "if (!accepted) return false")
  string(FIND "${settings}" "${text}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Android settings contract missing: ${text}")
  endif()
endforeach()
foreach(text "LoadAreaPresets" "Cancel and close" "ensureWidgetVisible" "Account" "QLineEdit::Password" "rememberUsername" "{\"none\",\"None\"}" "{\"offline-tidal\",\"Offline tidal package (.xtd)\"}" "return accepted ?")
  string(FIND "${generator}" "${text}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Android generator/navigation contract missing: ${text}")
  endif()
endforeach()
foreach(text "TPXO cache" "TPXO model" "&GRIBUICtrlBar::OnCompositeDialog, this")
  string(FIND "${generator}${panel}" "${text}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "Removed Android UI path returned: ${text}")
  endif()
endforeach()
# These are source-level guardrails; real touch, keyboard and cancellation
# behavior must still be checked on an Android device.
